library(ggplot2)
require(reshape2)
require(data.table)
Sys.setenv("plotly_username" = "TomHull")
Sys.setenv("plotly_api_key" = "taszfssmi1")
require(plotly)
Sys.setenv(https_proxy='http://localhost:80')
Sys.setenv(http_proxy='http://localhost:80')
setwd("working/")
require(cefasMOS)
print('MOS tools loaded')
