#' Fetch data from the biogeochemical database
#'
#' Tool to query the "data" view from the biogeochemical postgres database
#'
#' These data use the following flag scheme
#' \tabular{rr}{
#'    \strong{flag} \tab \strong{flag_description} \cr
#'     0 \tab         no quality control \cr
#'     1 \tab                 good value \cr
#'     2 \tab        probably good value \cr
#'     3 \tab         probably bad value \cr
#'     4 \tab                  bad value \cr
#'     5 \tab              changed value \cr
#'     6 \tab      value below detection \cr
#'     7 \tab            value in excess \cr
#'     8 \tab         interpolated value \cr
#'     9 \tab              missing value \cr
#'     A \tab value phenomenon uncertain \cr
#'     B \tab              nominal value
#' }
#'
#' @param survey a survey code, use '%' as a wildcard e.g. "CEND_%_18"
#' @param bbox a named vector bounding box (ymin, ymax, xmin, xmax) as generated by calc_bounding_box
#' @param after a time stamp after which data is selected e.g. "2018-01-01"
#' @param before a time stamp before which data is selected e.g. "2019-01-01"
#' @param parameters a vector of parameter codes default is c("SAL", "TOXN"), use parameters = "ALL" to select all.
#'
#' @return data.table
#' @export
#' @examples
#'\dontrun{
#' bbox = calc_bounding_box(52.2, 2, 500) # 1 km box centred on 52.2N 2E
#' dat = biogeochem.fetch(bbox = bbox)
#' dat = biogeochem.fetch(after = "2018-01-01", parameters = c("all"))
#'}
biogeochem.fetch <- function(survey = NA, bbox = NA, after = NA, before = NA, parameters = c("SAL", "TOxN")){
  con = DBI::dbConnect(
    drv = RPostgres::Postgres(),
    dbname = "biogeochem",
    host = "citprodpostgres01",
    port = 5432,
    application_name = "cefasMOS",
    user = "biogeochem_reader", password = "chemistr33")

  where = vector()
  if(!is.na(survey)){
    where = append(where, paste0("survey LIKE '", survey, "'"))
  }
  if(!is.na(bbox[1])){
    where = append(where, paste("lat >", bbox["ymin"], "AND",
           "lat <", bbox["ymax"], "AND",
           "lon >", bbox["xmin"], "AND",
           "lon <", bbox["xmax"]))
  }
  if(!is.na(after)){
    where = append(where, paste0("datetime > '", after, "'"))
  }
  if(!is.na(before)){
    where = append(where, paste0("datetime < '", before, "'"))
  }
  if(!any(grepl("ALL", parameters, ignore.case = T))){
    where = append(where, paste0("parameter IN ('", paste0(parameters, collapse = "','"), "')"))
  }
  q = paste("SELECT * FROM data WHERE", paste(where, collapse = " AND "))
  print(q)
  d = data.table::setDT(DBI::dbGetQuery(con, q))
  return(d)
}
