#' ESM2 live aquire reader
#'
#' reads live aquire files and plots output
#'
#' @details This function reads text files generated by the SmartBuoy interface live aquire.
#' @param file location of live aquire file, leave blank to use dialog box
#' @return a list containing a data frame and ggplot
#' @keywords smartbuoy esm2
#' @export
read.liveAquire <- function(file = dlgOpen(title = 'Open LiveAquire file...')$res){
    require(ggplot2)
    require(reshape2)
    require(data.table)
    require(svDialogs)
    require(stringr)
    
    x = fread(file)     # read in file
    x = x[,lapply(.SD, as.numeric)]     # convert all columns to numeric
    x = melt(x, id.vars = 'Seconds Elapsed')
    setnames(x, 'Seconds Elapsed', 'time')
    x[,depth := as.numeric(str_extract(variable, '\\d+.\\d(?=m)')), by = variable]
    x[,serial := str_extract(variable, '\\d+(?=,)'), by = variable]
    x[,channel := unlist(strsplit(as.character(variable), split = ':', fixed = T))[1], by = variable]
    x[,subchannel := unlist(strsplit(as.character(channel), split = '.', fixed = T))[2], by = variable]
    x[,par := unlist(strsplit(as.character(variable), split = ' ', fixed = T))[2], by = variable]
    dat = x
    plotpar = c('TEMP', 'COND', 'FLUORS', 'FTU', 'O2SAT', 'PAR')
    plot = ggplot(na.omit(x[par %in% plotpar,]), aes(time, value)) +
        geom_line(aes(color = variable)) +
        facet_grid(variable ~ .,scales='free') +
        theme_bw()
    return(list(dat, plot))
}